### ISSUE TITLE
Intermittent failure TestProducerSuccessLoopPanicsMsgNotInflight

### ISSUE THREAD

**Issue by peterbroadhurst** [hyperledger/firefly-ethconnect#179]
Little unclear what the error is in the below:
```
2021-11-23T01:05:24.8920728Z === RUN   TestProducerSuccessLoopPanicsMsgNotInflight
2021-11-23T01:05:24.8922004Z time="2021-11-23T01:05:24Z" level=debug msg="Kafka consumer loop started"
2021-11-23T01:05:24.8922967Z time="2021-11-23T01:05:24Z" level=debug msg="Kafka producer successes loop started"
2021-11-23T01:05:24.8923964Z time="2021-11-23T01:05:24Z" level=debug msg="Kafka producer successes loop started"
2021-11-23T01:05:24.8924976Z panic: Received confirmation for message not in in-flight map: badness
2021-11-23T01:05:24.8925469Z 
2021-11-23T01:05:24.8925850Z goroutine 73 [running]:
2021-11-23T01:05:24.8927203Z github.com/hyperledger/firefly-ethconnect/internal/kafka.(*KafkaBridge).ProducerSuccessLoop(0xc000236b40, 0xfa5810, 0xc00000fe30, 0xfa5848, 0xc0002760c0, 0xc00002f850)
2021-11-23T01:05:24.8929332Z 	/home/runner/work/firefly-ethconnect/firefly-ethconnect/ethconnect/internal/kafka/kafkabridge.go:410 +0x37e
2021-11-23T01:05:24.8930750Z created by github.com/hyperledger/firefly-ethconnect/internal/kafka.setupMocks
2021-11-23T01:05:24.8932283Z 	/home/runner/work/firefly-ethconnect/firefly-ethconnect/ethconnect/internal/kafka/kafkabridge_test.go:212 +0x2b5
2021-11-23T01:05:24.8933577Z FAIL	github.com/hyperledger/firefly-ethconnect/internal/kafka	0.052s
```

https://github.com/hyperledger/firefly-ethconnect/runs/4294017754?check_suite_focus=true

**Comment by peterbroadhurst** [comment]
Ah, looks like a go routine might be kicked off in the background, as well as the one that's intended to run in the test.
